const $=s=>document.querySelector(s);
const image=(n,caption)=>`<button class="image-button" data-image="${n}" aria-label="放大${caption}"><img class="full-image" src="assets/portfolio-${n}.jpg" alt="${caption}" loading="lazy"></button><div class="image-caption">${caption} / 点击放大</div>`;
const folio=(name,n)=>`<div class="folio"><span>HU JUNYAO / ${name}</span><span>${String(n).padStart(2,'0')}</span></div>`;
const leaf=(html)=>`<article class="leaf">${html}</article>`;
const chapters=[
 {name:'自我介绍',color:'#d5ddc2',ink:'#303e30',left:`<span class="eyebrow">01 / ABOUT ME</span><h1>你好，<br>我是胡军瑶。</h1><div class="lede">对音乐影像和娱乐内容保持热爱。</div><p>广播电视编导专业背景。<br>从校园影像创作，到音乐平台内容运营，<br>再到综艺与活动现场，这是我的创作经历。</p><button class="text-link" data-audio>听听我做的 Demo ↗</button>${folio('INTRODUCTION',1)}`,right:`<div class="portrait-frame"><img src="assets/profile-color.jpg" alt="胡军瑶个人照片"><div class="portrait-note">很高兴，在这里认识你。</div></div><div class="intro-details"><div><b>吉林动画学院</b><span>2026 届 · 广播电视编导</span></div><div><b>福建</b><span>籍贯</span></div><div><b>ENFP / 白羊座</b><span>关于我的小标签</span></div></div>${folio('NICE TO MEET YOU',2)}`},
 {name:'教育经历',color:'#ded5bf',ink:'#453b2f',left:`<span class="eyebrow">02 / EDUCATION</span><h1>教育背景</h1><h2 class="school-title">吉林动画学院</h2><p>2022—2026 / 本科 / 广播电视编导</p><p class="grade">均分 90+</p><div class="timeline-row"><strong>专业排名全系第二 · 班级第一</strong><p>优秀毕业生</p></div><p class="education-tools">熟练使用 WPS 等办公软件；PR、PS、AE、剪映等剪辑软件；可灵、即梦等AI视频生成软件。</p>${folio('EDUCATION',3)}`,right:`<span class="eyebrow">SUMMER STUDY / 2025</span><h2 class="school-title">延世大学<br>Yonsei University</h2><p>Media Communication 暑期课程</p><div class="timeline-row"><strong>韩流数字内容与跨文化传播</strong><p>研究韩国媒体生态、内容策划与传播。</p></div><div class="timeline-row"><strong>《韩流文化的全球适应性策略演变》</strong><p>小组课题中负责核心内容解读，获 A 成绩结业。</p></div><div class="metrics"><div><b>7.0</b><span>IELTS</span></div><div><b>4 级</b><span>韩语 TOPIK</span></div></div>${folio('A WIDER PERSPECTIVE',4)}`},
 {name:'实习 / 腾讯音乐',color:'#bacbd1',ink:'#293f49',left:`<span class="eyebrow">03 / INTERNSHIP · 2025.10—2026.04</span><h1>腾讯音乐<br>娱乐集团</h1><h3>新媒体运营实习生</h3><p>全平台账号矩阵运营、音乐视频制作、<br>线下活动拍摄与艺人宣发。</p><div class="timeline-row"><strong>QQ音乐海外现场 / 独立运营</strong><p>内容规划 → 选题 → 剪辑 → 发布 → 数据复盘</p></div><div class="metrics"><div><b>3416.5万</b><span>材料所述 30 天播放量</span></div><div><b>7.6万</b><span>同统计窗口涨粉</span></div></div><p class="small">数据来自原作品集，具体统计日期待补充。</p>${folio('TENCENT MUSIC',5)}`,right:`<span class="eyebrow">SELECTED CONTENT</span>${image('07','QQ音乐视频与图文作品')}<div class="project-links"><button data-work="QQ音乐海外现场视频作品">海外现场 / K-pop 内容 <span>↗</span></button><button data-work="QQ音鹅 IP 作品">QQ音鹅 / IP 图文与视频 <span>↗</span></button><button data-work="艺人宣发与现场拍摄作品">艺人宣发 / 活动拍摄 <span>↗</span></button></div>${folio('CONTENT & COMMUNITY',6)}`},
 {name:'实习 / 网易云音乐',color:'#d2b5a5',ink:'#51352c',left:`<span class="eyebrow">04 / INTERNSHIP · 2024.06—2024.10</span><h1>网易云音乐</h1><h3>内容运营实习生</h3><p class="lede">从 0 到 1，<br>搭建一个音乐内容专区。</p><div class="timeline-row"><strong>法语音乐专区</strong><p>项目排期、专区框架、歌单矩阵与内容分发。</p></div><div class="timeline-row"><strong>内容与视觉</strong><p>选曲、文案、合规审核，歌单封面与 Banner 设计。</p></div><div class="metrics"><div><b>1000万+</b><span>核心爆款歌单播放量 / 原材料所述</span></div></div>${folio('NETEASE CLOUD MUSIC',7)}`,right:`<span class="eyebrow">CONTENT / DESIGN / OPERATIONS</span>${image('08','网易云音乐法语音乐专区')}<p>持续维护歌单与推荐位，同时参与粤语、经典、K-pop 等内容品类的运营。</p><button class="text-link" data-work="网易云音乐法语音乐专区">查看专区与视觉作品 ↗</button>${folio('FROM ZERO TO ONE',8)}`},
 {name:'实习 / 芒果 TV',color:'#dec188',ink:'#564025',left:`<span class="eyebrow">05 / INTERNSHIP · 2023.06—2023.09</span><h1>芒果 TV</h1><h3>总裁办 · 执行统筹实习生</h3><p class="lede">从创意到现场，<br>让每一个环节落地。</p><div class="timeline-row"><strong>《马栏山芒果节 · 不设限毕业礼》</strong><p>参与前期策划、流程拆解、跨部门对接与现场执行。</p></div><div class="timeline-row"><strong>综艺内容审查</strong><p>参与成片审看、敏感信息筛查与剪辑优化建议。</p></div>${folio('MANGO TV',9)}`,right:`<span class="eyebrow">BEHIND THE SCENES</span>${image('09','芒果TV活动与综艺经历')}<button class="text-link" data-work="芒果TV活动与综艺项目">查看活动与执行记录 ↗</button>${folio('PLAN TO PRODUCTION',10)}`},
 {name:'实习 / 湖南娱乐',color:'#bfc7b4',ink:'#364631',left:`<span class="eyebrow">06 / INTERNSHIP · 2022.12—2023.02</span><h1>湖南娱乐</h1><h3>新媒体运营实习生</h3><p>官方账号内容运维、物料剪辑与全网宣发，<br>采访统筹、拍摄执行与短视频策划。</p><div class="timeline-row"><strong>内容策划与制作</strong><p>从选题、脚本到拍摄落地，参与完整制作流程。</p></div><button class="text-link" data-work="湖南娱乐新媒体视频作品">打开我的实习作品 ↗</button>${folio('HUNAN ENTERTAINMENT',11)}`,right:`<span class="eyebrow">VIDEO & PUBLICITY</span>${image('10','湖南娱乐视频作品')}<p class="small">后续在此接入视频原文件，点击即可站内播放。</p>${folio('STORIES ON SCREEN',12)}`},
 {name:'项目 / 开始推理吧4',color:'#a7bac0',ink:'#283f48',left:`<span class="eyebrow">07 / PROJECT · 2026.05—2026.06</span><h1>开始推理吧<br>第四季</h1><h3>机美与执行导演</h3><div class="timeline-row"><strong>美术置景与场景搭建</strong><p>根据剧本逻辑规划场景，统筹舞美与道具落地，兼顾多机位拍摄。</p></div><div class="timeline-row"><strong>录制现场执行</strong><p>对接摄像、灯光、艺统等部门，推进现场调度。</p></div>${folio('PROJECT EXPERIENCE',13)}`,right:`<span class="eyebrow">ON SET</span>${image('11','开始推理吧4场景与执行记录')}<button class="text-link" data-work="开始推理吧第四季现场记录">查看现场记录 ↗</button>${folio('SCENE & EXECUTION',14)}`},
 {name:'在校创作 / 导演作品',color:'#c7b9ce',ink:'#493952',left:`<span class="eyebrow">08 / CAMPUS CREATIONS</span><h1>三地<br>三摇篮</h1><p class="lede">系列影像作品</p><h2>总导演 / 胡军瑶</h2><p>这里收录我在学校担任总导演的<br>一汽汽车篇与长影篇。</p><p class="small">作品封面、正片与创作过程将在素材整理后补充。</p>${folio('DIRECTED BY HU JUNYAO',15)}`,right:`<span class="eyebrow">DIRECTOR’S COLLECTION</span><div class="school-cards"><button class="school-card" data-work="《三地三摇篮》一汽汽车篇" data-role="总导演"><small>FILM / 01</small><strong>一汽汽车篇</strong><span>总导演 · 视频待补充 ↗</span></button><button class="school-card" data-work="《三地三摇篮》长影篇" data-role="总导演"><small>FILM / 02</small><strong>长影篇</strong><span>总导演 · 视频待补充 ↗</span></button></div>${folio('CAMPUS FILMS',16)}`},
 {name:'在校创作 / 融媒体',color:'#cbd0ac',ink:'#3f482d',left:`<span class="eyebrow">09 / CAMPUS MEDIA</span><h1>校园里的<br>新闻现场。</h1><h3>校融媒体中心 · 部长</h3><p>学校官方新闻制作，以及微博、抖音、<br>bilibili、公众号等平台的内容运营。</p><div class="timeline-row"><strong>策划、制作与内容审核</strong><p>拍摄方案、文案策划、官方内容生产与执行。</p></div><button class="text-link" data-work="学校官方新闻制作" data-role="校融媒体中心部长 / 新闻制作">查看学校官方新闻作品 ↗</button>${folio('CAMPUS MEDIA CENTER',17)}`,right:`<span class="eyebrow">OFFICIAL NEWS & CONTENT</span>${image('12','校融媒体中心内容记录')}<p class="small">保留原作品集在校经历，并增加学校新闻视频入口。</p>${folio('REPORT / CREATE / CONNECT',18)}`},
 {name:'核心技能',color:'#d4c8b5',ink:'#453d30',left:`<span class="eyebrow">10 / SKILLS</span><h1>从想法，<br>到成片。</h1><div class="skills"><div><strong>影像与视觉</strong><p>PR / AE / PS / 剪映</p></div><div><strong>音频制作</strong><p>AU / Logic Pro</p></div><div><strong>AI 辅助创作</strong><p>可灵 / 即梦</p></div><div><strong>语言</strong><p>雅思 7.0 / TOPIK 4 级</p></div></div>${folio('TOOLKIT',19)}`,right:`<span class="eyebrow">HOW I WORK</span><h2>内容、协作与执行。</h2><div class="timeline-row"><strong>内容策划与运营</strong><p>选题、脚本、制作、发布与数据复盘。</p></div><div class="timeline-row"><strong>项目推进</strong><p>排期规划、跨部门协调与现场执行。</p></div><div class="timeline-row"><strong>持续创作</strong><p>把对音乐和娱乐的兴趣，继续做成作品。</p></div><button class="text-link" data-audio>听我的音乐 Demo ↗</button>${folio('KEEP MAKING',20)}`},
 {name:'联系我',color:'#c4ccb8',ink:'#344331',left:`<span class="eyebrow">11 / THANK YOU</span><h1>感谢翻阅，<br>期待下一次<br>一起创作。</h1><p class="lede">胡军瑶</p>${folio('END OF THIS CHAPTER',21)}`,right:`<span class="eyebrow">LET’S TALK</span><h2>保持联系。</h2><a class="contact-email" href="mailto:225961555@qq.com">225961555@qq.com ↗</a><a href="tel:15060371385">15060371385</a><p>求职意向城市 / 北京</p><button class="text-link" data-jump="0">回到自我介绍 ↗</button><button class="text-link" data-audio>再听一遍 Demo ↗</button>${folio('TO BE CONTINUED',22)}`}
];
let current=0,opened=false,busy=false;const spread=$('#spread'),book=$('#book');
function markup(c){const names=['About me','Education','Music & moments','A new chapter','Behind the scenes','On the screen','On set','My films','Campus diary','Little skills','Keep in touch'];const left=c.left.replace('</span>','</span><div class="chapter-script">'+names[chapters.indexOf(c)]+'</div>');return leaf(left)+leaf(c.right+'<span class="leaf-sticker" aria-hidden="true">made<br>with love</span>')}
function update(){const c=chapters[current];spread.innerHTML=markup(c);spread.style.setProperty('--paper',c.color);spread.style.setProperty('--ink',c.ink);$('#chapter-label').textContent=c.name;$('#page-number').textContent=`${String(current+1).padStart(2,'0')} / ${chapters.length}`;$('#previous').disabled=current===0;$('#next').disabled=current===chapters.length-1;document.querySelectorAll('[data-dot]').forEach((b,i)=>{if(i===current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});spread.scrollTop=0}
function openBook(target=0){current=target;if(opened){update();return}opened=true;$('#opening').classList.add('closing');setTimeout(()=>{$('#opening').hidden=true;$('#reading').hidden=false;$('#reading').classList.add('enter');update();$('#next').focus({preventScroll:true})},450)}
function go(n){if(n<0||n>=chapters.length||busy)return;if(!opened){openBook(n);return}if(n===current)return;busy=true;const old=spread.cloneNode(true);old.removeAttribute('id');old.classList.add('turn-layer');if(n<current)old.classList.add('reverse');old.setAttribute('aria-hidden','true');old.inert=true;book.append(old);current=n;update();setTimeout(()=>{old.remove();busy=false},650)}
$('#dots').innerHTML=chapters.map((c,i)=>`<button style="--dot:${c.color}" data-dot="${i}" aria-label="${c.name}" title="${c.name}"></button>`).join('');$('#toc-items').innerHTML=chapters.map((c,i)=>`<button class="toc-entry" data-jump="${i}"><span>${String(i+1).padStart(2,'0')}　${c.name}</span><small>↗</small></button>`).join('');
$('#open-book').onclick=()=>openBook();$('#open-caption').onclick=()=>openBook();$('#previous').onclick=()=>go(current-1);$('#next').onclick=()=>go(current+1);$('#contents').onclick=()=>$('#toc').showModal();$('#home').onclick=()=>{if(busy)return;opened=false;$('#reading').hidden=true;$('#opening').hidden=false;$('#opening').classList.remove('closing')};$('#footer-contact').onclick=()=>go(chapters.length-1);
document.addEventListener('click',e=>{const dot=e.target.closest('[data-dot]');if(dot)go(+dot.dataset.dot);const jump=e.target.closest('[data-jump]');if(jump){$('#toc').close();go(+jump.dataset.jump)}const close=e.target.closest('[data-close]');if(close)$('#'+close.dataset.close).close();if(e.target.closest('[data-audio]'))showAudio();const img=e.target.closest('[data-image]');if(img){$('#work-content').innerHTML=`<span class="eyebrow">ORIGINAL PORTFOLIO</span><h2>原作品集页面</h2><img src="assets/portfolio-${img.dataset.image}.jpg" alt="原作品集页面">`;$('#work-dialog').showModal()}const w=e.target.closest('[data-work]');if(w){$('#work-content').innerHTML=`<span class="eyebrow">SELECTED WORK</span><h2></h2>${w.dataset.role?'<p class="work-role"></p>':''}<div class="media-placeholder">视频与作品素材待补充<small>收到原文件后，这里可直接播放。</small></div>`;$('#work-content h2').textContent=w.dataset.work;if(w.dataset.role)$('#work-content .work-role').textContent='我的职责：'+w.dataset.role;$('#work-dialog').showModal()}});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.target.matches('input'))return;if(e.key==='Escape'){$('#audio-panel').hidden=true;return}if(!opened)return;if(e.key==='ArrowRight'){e.preventDefault();go(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(current-1)}});
let startX=0,startY=0;book.addEventListener('touchstart',e=>{startX=e.changedTouches[0].clientX;startY=e.changedTouches[0].clientY},{passive:true});book.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.5)go(current+(dx<0?1:-1))},{passive:true});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
const audio=$('#audio');audio.volume=.7;function showAudio(){$('#audio-panel').hidden=false}$('#sound-open').onclick=showAudio;$('#audio-close').onclick=()=>{$('#audio-panel').hidden=true};async function toggle(){try{if(audio.paused)await audio.play();else audio.pause()}catch(e){$('#audio-status').textContent='播放失败，请重试'}}$('#play').onclick=toggle;$('#cd').onclick=toggle;$('#audio-toggle').onclick=toggle;
function state(){document.body.classList.toggle('is-playing',!audio.paused);$('#play').textContent=audio.paused?'播放我的 Demo ↗':'暂停播放 Ⅱ';$('#audio-toggle').setAttribute('aria-label',audio.paused?'播放 Demo':'暂停 Demo');$('#audio-status').textContent=audio.paused?'READY TO LISTEN':'NOW PLAYING / HU JUNYAO'}const fmt=t=>Number.isFinite(t)?`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`:'--:--';function progress(){$('#elapsed').textContent=fmt(audio.currentTime);$('#duration').textContent=fmt(audio.duration);$('#progress').value=audio.duration?audio.currentTime/audio.duration*100:0}audio.addEventListener('play',state);audio.addEventListener('pause',state);audio.addEventListener('ended',state);audio.addEventListener('timeupdate',progress);audio.addEventListener('loadedmetadata',progress);audio.addEventListener('error',()=>$('#audio-status').textContent='音频加载失败，请刷新重试');$('#progress').oninput=e=>{if(Number.isFinite(audio.duration))audio.currentTime=+e.target.value/100*audio.duration};$('#audio-volume').oninput=e=>audio.volume=+e.target.value;
$('#cd-scene').addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();$('#cd').style.transform=`rotateX(${27-(e.clientY-r.top-r.height/2)*.12}deg) rotateY(${-22+(e.clientX-r.left-r.width/2)*.15}deg) rotateZ(-18deg)`});$('#cd-scene').addEventListener('pointerleave',()=>$('#cd').style.transform='');update();
